
  kafka:
    hostname: kafka-connect
    image: confluentinc/cp-kafka-connect:5.0.0
    container_name: kafka-connect
    environment:
      - CONNECT_PRODUCER_INTERCEPTOR_CLASSES=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
      - CONNECT_CONSUMER_INTERCEPTOR_CLASSES=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
      - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
      - CONNECT_REST_PORT=8082
      - CONNECT_GROUP_ID="quickstart"
      - CONNECT_CONFIG_STORAGE_TOPIC="quickstart-config"
      - CONNECT_OFFSET_STORAGE_TOPIC="quickstart-offsets"
      - CONNECT_STATUS_STORAGE_TOPIC="quickstart-status"
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
      - CONNECT_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
      - CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
      - CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
      - CONNECT_REST_ADVERTISED_HOST_NAME="kafka-connect"
      - CONNECT_LOG4J_ROOT_LOGLEVEL=DEBUG
      - CONNECT_PLUGIN_PATH=/usr/share/java
      - CONNECT_REST_HOST_NAME="kafka-connect"
    networks:
      - confluent
    volumes:
      - /tmp/quickstart/file:/tmp/quickstart
